site_name: Spot Oscillation and Planet
site_description: "High-fidelity analysis of stellar spots and planetary transits"
site_author: "Eduardo Cristo"

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  repo_url: https://github.com/EduardoCristo/SOAP-Spot-Oscillation-And-Planet-code
  repo_name: GitHub "SOAP"
  features:
    - navigation.expand: true
    - navigation.top
    - header.autohide        # Hide header on scroll for cleaner reading
    - toc.integrate         # Integrate table of contents in page sidebar

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            group_by_category: true
            members_order: alphabetical
            show_source: false   # Hide source code links for clarity
            show_root_toc_entry: false
  - mkdocs-jupyter:
      execute: false           # Automatically run notebooks at build time for up-to-date outputs
      include_source: true
      kernel_name: python3

docs_dir: docs

nav:
  - Home: index.md
  - Install: install.md
  - Examples:
      - Basic Example: notebooks/compare_batman.ipynb
      - Complex: notebooks/Sun_jupiter_phoenix.ipynb
  - API Reference: reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EduardoCristo/SOAP-Spot-Oscillation-And-Planet-code
  footer:
    copyright: "© 2025 Eduardo Cristo"