site_name: Spot Oscillation and Planet
site_author: "Eduardo Cristo"

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes 
    - toc.integrate 
    - content.code.copy
    - content.code.select
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Install: install.md
  - Examples:
      - Basic Example: notebooks/compare_batman.ipynb
      - Complex: notebooks/Sun_jupiter_phoenix.ipynb
  - API Reference: reference.md

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [SOAP]
          options:
            filters:
              - "!^_"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EduardoCristo/SOAP-Spot-Oscillation-And-Planet-code
  footer:
    copyright: "© 2025 Eduardo Cristo"